changed domain path
internetee/epp-xml pull request #12
Opened 2021-06-11 13:27 UTC by OlegPhenomenon

2021-06-14 12:02 UTC, yulgolem commented on lib/client_transaction_id.rb
> +    @schema_version = args[:schema_version]
Do we have any default values or 'nil' arguments will break the gem?
If so - we are breaking backward comparability and we need to raise major gem version.

2021-06-14 12:03 UTC, yulgolem requested changes

2021-06-14 12:03 UTC, yulgolem commented on lib/epp-xml/domain.rb
> +      # XMLNS_DOMAIN  = 'https://epp.tld.ee/schema/domain-eis-1.0.xsd'.freeze
Could you, please, clean the unused code?

2021-06-16 07:42 UTC, yulgolem approved these changes

2021-06-16 08:48 UTC, vohmar commented
related to https://github.com/internetee/registry/issues/2004
related to https://github.com/internetee/registry/issues/2030

2021-06-16 08:49 UTC, merged